version: 2
jobs:
    build_py3:
        working_directory: ~/bulstem-py
        docker:
            - image: circleci/python:3.5
        steps:
            - checkout
            - run: sudo pip install --progress-bar off .
            - run: sudo pip install nltk
            - run: python -m unittest tests.bulstem_test
    build_py2:
        working_directory: ~/pytorch-pretrained-BERT
        docker:
            - image: circleci/python:2.7
        steps:
            - checkout
            - run: sudo pip install --progress-bar off .
            - run: sudo pip install -r requirments.txt
            - run: python -m unittest tests.bulstem_test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py3
      - build_py2
