version: 2
jobs:
    build_py3:
        working_directory: ~/bulstem-py
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run: pip install -e ".[testing]" --user
            - run: pip install -r requirements-test.txt --user
            - run:
                name: Run Tests
                command: |
                  $HOME/.local/bin/coverage run --source=./ -m pytest
                  $HOME/.local/bin/coverage report
                  $HOME/.local/bin/coverage html  # open htmlcov/index.html in a browser
            - store_artifacts:
                path: htmlcov
    check_code_quality:
        working_directory: ~/bulstem-py
        docker:
            - image: circleci/python:3.6
        parallelism: 1
        steps:
            - checkout
            - run: pip install -r requirements-test.txt --user --no-cache-dir
            - run: black --check --target-version py36 bulstem tests
            - run: isort --check-only --recursive bulstem tests
            - run: flake8 bulstem tests
            - run: pylint bulstem tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py3
      - check_code_quality
